### ISSUE TITLE
the difference between sklearn.KNNImputer and missingpy.KNNImputer

### ISSUE THREAD

**Issue by jckkvs** [epsilon-machine/missingpy#34]
I compared each source code and the algorithms look almost the same. Was missingpy ported to sklearn?

**Comment by ashimb9** [comment]
Hi! I am the lead developer of SKlearn's KNNImputer and also of this (missingpy) package. KNNImputer was released as part of this package while it went through the review process of Scikit Learn's maintainers so that folks would be able to use it while that process took its course. That is probably why you noticed the similarity between the two packages. I would recommend using the Scikit Learn version at this point since that has been merged into the core SKLearn package.
